version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "weather_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5405:5432"
